# Generated by Django 5.0.2 on 2024-02-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='SKU',
            new_name='sku',
        ),
    ]
