# Generated by Django 5.0.2 on 2024-02-12 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_alter_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
    ]
