# Generated by Django 5.0.2 on 2024-02-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Category',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
