# Generated by Django 5.0.2 on 2024-02-12 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Category',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.category'),
            preserve_default=False,
        ),
    ]
